/**
 * This file is part of ankus.
 *
 * ankus is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * ankus is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with ankus.  If not, see <http://www.gnu.org/licenses/>.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.21 at 10:54:40 오전 KST 
//


package com.ankus.model.collector;

import javax.xml.bind.annotation.*;
import java.io.Serializable;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.openankus.org/schema/collector}sourceDirectory"/>
 *         &lt;element name="workingDirectory" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="completeDirectory" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="removeAfterCopy" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="errorDirectory" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sourceDirectory",
    "workingDirectory",
    "completeDirectory",
    "removeAfterCopy",
    "errorDirectory"
})
@XmlRootElement(name = "fromLocal")
public class FromLocal implements Serializable {

    @XmlElement(required = true)
    protected SourceDirectory sourceDirectory;
    @XmlElement(required = true)
    protected String workingDirectory;
    @XmlElement(required = true)
    protected String completeDirectory;
    @XmlElement(defaultValue = "false")
    protected boolean removeAfterCopy;
    @XmlElement(required = true)
    protected String errorDirectory;

    /**
     * Gets the value of the sourceDirectory property.
     * 
     * @return
     *     possible object is
     *     {@link SourceDirectory }
     *     
     */
    public SourceDirectory getSourceDirectory() {
        return sourceDirectory;
    }

    /**
     * Sets the value of the sourceDirectory property.
     * 
     * @param value
     *     allowed object is
     *     {@link SourceDirectory }
     *     
     */
    public void setSourceDirectory(SourceDirectory value) {
        this.sourceDirectory = value;
    }

    /**
     * Gets the value of the workingDirectory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorkingDirectory() {
        return workingDirectory;
    }

    /**
     * Sets the value of the workingDirectory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorkingDirectory(String value) {
        this.workingDirectory = value;
    }

    /**
     * Gets the value of the completeDirectory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompleteDirectory() {
        return completeDirectory;
    }

    /**
     * Sets the value of the completeDirectory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompleteDirectory(String value) {
        this.completeDirectory = value;
    }

    /**
     * Gets the value of the removeAfterCopy property.
     * 
     */
    public boolean isRemoveAfterCopy() {
        return removeAfterCopy;
    }

    /**
     * Sets the value of the removeAfterCopy property.
     * 
     */
    public void setRemoveAfterCopy(boolean value) {
        this.removeAfterCopy = value;
    }

    /**
     * Gets the value of the errorDirectory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrorDirectory() {
        return errorDirectory;
    }

    /**
     * Sets the value of the errorDirectory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrorDirectory(String value) {
        this.errorDirectory = value;
    }

}
