/**
 * This file is part of ankus.
 *
 * ankus is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * ankus is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with ankus.  If not, see <http://www.gnu.org/licenses/>.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.21 at 10:54:40 오전 KST 
//


package com.ankus.model.collector;

import javax.xml.bind.annotation.*;
import java.io.Serializable;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="handler" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ingress" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="egress" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "mapping")
public class Mapping implements Serializable {

    @XmlAttribute(name = "handler", required = true)
    protected String handler;
    @XmlAttribute(name = "ingress", required = true)
    protected String ingress;
    @XmlAttribute(name = "egress", required = true)
    protected String egress;

    /**
     * Gets the value of the handler property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHandler() {
        return handler;
    }

    /**
     * Sets the value of the handler property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHandler(String value) {
        this.handler = value;
    }

    /**
     * Gets the value of the ingress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIngress() {
        return ingress;
    }

    /**
     * Sets the value of the ingress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIngress(String value) {
        this.ingress = value;
    }

    /**
     * Gets the value of the egress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEgress() {
        return egress;
    }

    /**
     * Sets the value of the egress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEgress(String value) {
        this.egress = value;
    }

}
