/**
 * This file is part of ankus.
 *
 * ankus is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * ankus is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with ankus.  If not, see <http://www.gnu.org/licenses/>.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.21 at 10:54:40 오전 KST 
//


package com.ankus.model.collector;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ankus.model.collector package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ankus.model.collector
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Mkdir }
     * 
     */
    public Mkdir createMkdir() {
        return new Mkdir();
    }

    /**
     * Create an instance of {@link Selector }
     * 
     */
    public Selector createSelector() {
        return new Selector();
    }

    /**
     * Create an instance of {@link Output }
     * 
     */
    public Output createOutput() {
        return new Output();
    }

    /**
     * Create an instance of {@link Prepare }
     * 
     */
    public Prepare createPrepare() {
        return new Prepare();
    }

    /**
     * Create an instance of {@link Copy }
     * 
     */
    public Copy createCopy() {
        return new Copy();
    }

    /**
     * Create an instance of {@link Variable }
     * 
     */
    public Variable createVariable() {
        return new Variable();
    }

    /**
     * Create an instance of {@link FromLocal }
     * 
     */
    public FromLocal createFromLocal() {
        return new FromLocal();
    }

    /**
     * Create an instance of {@link SourceDirectory }
     * 
     */
    public SourceDirectory createSourceDirectory() {
        return new SourceDirectory();
    }

    /**
     * Create an instance of {@link ToHdfs }
     * 
     */
    public ToHdfs createToHdfs() {
        return new ToHdfs();
    }

    /**
     * Create an instance of {@link Collector }
     * 
     */
    public Collector createCollector() {
        return new Collector();
    }

    /**
     * Create an instance of {@link Description }
     * 
     */
    public Description createDescription() {
        return new Description();
    }

    /**
     * Create an instance of {@link Move }
     * 
     */
    public Move createMove() {
        return new Move();
    }

    /**
     * Create an instance of {@link Input }
     * 
     */
    public Input createInput() {
        return new Input();
    }

    /**
     * Create an instance of {@link ToLocal }
     * 
     */
    public ToLocal createToLocal() {
        return new ToLocal();
    }

    /**
     * Create an instance of {@link Policy }
     * 
     */
    public Policy createPolicy() {
        return new Policy();
    }

    /**
     * Create an instance of {@link Schedule.MisfireInstructions }
     * 
     */
    public Schedule.MisfireInstructions createScheduleMisfireInstructions() {
        return new Schedule.MisfireInstructions();
    }

    /**
     * Create an instance of {@link End }
     * 
     */
    public End createEnd() {
        return new End();
    }

    /**
     * Create an instance of {@link Header }
     * 
     */
    public Header createHeader() {
        return new Header();
    }

    /**
     * Create an instance of {@link Variables }
     * 
     */
    public Variables createVariables() {
        return new Variables();
    }

    /**
     * Create an instance of {@link Policy.Ingress }
     * 
     */
    public Policy.Ingress createPolicyIngress() {
        return new Policy.Ingress();
    }

    /**
     * Create an instance of {@link Args }
     * 
     */
    public Args createArgs() {
        return new Args();
    }

    /**
     * Create an instance of {@link Properties }
     * 
     */
    public Properties createProperties() {
        return new Properties();
    }

    /**
     * Create an instance of {@link FromHttp }
     * 
     */
    public FromHttp createFromHttp() {
        return new FromHttp();
    }

    /**
     * Create an instance of {@link Cluster }
     * 
     */
    public Cluster createCluster() {
        return new Cluster();
    }

    /**
     * Create an instance of {@link Start }
     * 
     */
    public Start createStart() {
        return new Start();
    }

    /**
     * Create an instance of {@link Envs }
     * 
     */
    public Envs createEnvs() {
        return new Envs();
    }

    /**
     * Create an instance of {@link Schedule }
     * 
     */
    public Schedule createSchedule() {
        return new Schedule();
    }

    /**
     * Create an instance of {@link GlobalVariables }
     * 
     */
    public GlobalVariables createGlobalVariables() {
        return new GlobalVariables();
    }

    /**
     * Create an instance of {@link GlobalVariable }
     * 
     */
    public GlobalVariable createGlobalVariable() {
        return new GlobalVariable();
    }

    /**
     * Create an instance of {@link FromHttp.Method }
     * 
     */
    public FromHttp.Method createFromHttpMethod() {
        return new FromHttp.Method();
    }

    /**
     * Create an instance of {@link ClusterName }
     * 
     */
    public ClusterName createClusterName() {
        return new ClusterName();
    }

    /**
     * Create an instance of {@link Ftp.After }
     * 
     */
    public Ftp.After createFtpAfter() {
        return new Ftp.After();
    }

    /**
     * Create an instance of {@link Delete }
     * 
     */
    public Delete createDelete() {
        return new Delete();
    }

    /**
     * Create an instance of {@link Policy.Egress }
     * 
     */
    public Policy.Egress createPolicyEgress() {
        return new Policy.Egress();
    }

    /**
     * Create an instance of {@link Mapping }
     * 
     */
    public Mapping createMapping() {
        return new Mapping();
    }

    /**
     * Create an instance of {@link Compression }
     * 
     */
    public Compression createCompression() {
        return new Compression();
    }

    /**
     * Create an instance of {@link Headers }
     * 
     */
    public Headers createHeaders() {
        return new Headers();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link Job }
     * 
     */
    public Job createJob() {
        return new Job();
    }

    /**
     * Create an instance of {@link Clusters }
     * 
     */
    public Clusters createClusters() {
        return new Clusters();
    }

    /**
     * Create an instance of {@link com.ankus.model.collector.Egress }
     * 
     */
    public com.ankus.model.collector.Egress createEgress() {
        return new com.ankus.model.collector.Egress();
    }

    /**
     * Create an instance of {@link Ftp }
     * 
     */
    public Ftp createFtp() {
        return new Ftp();
    }

    /**
     * Create an instance of {@link Shell }
     * 
     */
    public Shell createShell() {
        return new Shell();
    }

}
