/**
 * This file is part of ankus.
 *
 * ankus is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * ankus is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with ankus.  If not, see <http://www.gnu.org/licenses/>.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.21 at 10:54:40 오전 KST 
//


package com.ankus.model.collector;

import javax.xml.bind.annotation.*;
import java.io.Serializable;


/**
 * <p>Java class for anonymous complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ingress">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element ref="{http://www.openankus.org/schema/collector}fromLocal"/>
 *                   &lt;element ref="{http://www.openankus.org/schema/collector}fromHttp"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="egress">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element ref="{http://www.openankus.org/schema/collector}toLocal"/>
 *                   &lt;element ref="{http://www.openankus.org/schema/collector}toHdfs"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "ingress",
        "egress"
})
@XmlRootElement(name = "policy")
public class Policy implements Serializable {

    @XmlElement(required = true)
    protected Policy.Ingress ingress;
    @XmlElement(required = true)
    protected Policy.Egress egress;

    /**
     * Gets the value of the ingress property.
     *
     * @return possible object is
     *         {@link Policy.Ingress }
     */
    public Policy.Ingress getIngress() {
        return ingress;
    }

    /**
     * Sets the value of the ingress property.
     *
     * @param value allowed object is
     *              {@link Policy.Ingress }
     */
    public void setIngress(Policy.Ingress value) {
        this.ingress = value;
    }

    /**
     * Gets the value of the egress property.
     *
     * @return possible object is
     *         {@link Policy.Egress }
     */
    public Policy.Egress getEgress() {
        return egress;
    }

    /**
     * Sets the value of the egress property.
     *
     * @param value allowed object is
     *              {@link Policy.Egress }
     */
    public void setEgress(Policy.Egress value) {
        this.egress = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * <p/>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p/>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element ref="{http://www.openankus.org/schema/collector}toLocal"/>
     *         &lt;element ref="{http://www.openankus.org/schema/collector}toHdfs"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "toLocal",
            "toHdfs"
    })
    public static class Egress implements Serializable {

        protected ToLocal toLocal;
        protected ToHdfs toHdfs;

        /**
         * Gets the value of the toLocal property.
         *
         * @return possible object is
         *         {@link ToLocal }
         */
        public ToLocal getToLocal() {
            return toLocal;
        }

        /**
         * Sets the value of the toLocal property.
         *
         * @param value allowed object is
         *              {@link ToLocal }
         */
        public void setToLocal(ToLocal value) {
            this.toLocal = value;
        }

        /**
         * Gets the value of the toHdfs property.
         *
         * @return possible object is
         *         {@link ToHdfs }
         */
        public ToHdfs getToHdfs() {
            return toHdfs;
        }

        /**
         * Sets the value of the toHdfs property.
         *
         * @param value allowed object is
         *              {@link ToHdfs }
         */
        public void setToHdfs(ToHdfs value) {
            this.toHdfs = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * <p/>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p/>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element ref="{http://www.openankus.org/schema/collector}fromLocal"/>
     *         &lt;element ref="{http://www.openankus.org/schema/collector}fromHttp"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "fromLocal",
            "fromHttp"
    })
    public static class Ingress implements Serializable {

        protected FromLocal fromLocal;
        protected FromHttp fromHttp;

        /**
         * Gets the value of the fromLocal property.
         *
         * @return possible object is
         *         {@link FromLocal }
         */
        public FromLocal getFromLocal() {
            return fromLocal;
        }

        /**
         * Sets the value of the fromLocal property.
         *
         * @param value allowed object is
         *              {@link FromLocal }
         */
        public void setFromLocal(FromLocal value) {
            this.fromLocal = value;
        }

        /**
         * Gets the value of the fromHttp property.
         *
         * @return possible object is
         *         {@link FromHttp }
         */
        public FromHttp getFromHttp() {
            return fromHttp;
        }

        /**
         * Sets the value of the fromHttp property.
         *
         * @param value allowed object is
         *              {@link FromHttp }
         */
        public void setFromHttp(FromHttp value) {
            this.fromHttp = value;
        }

    }

}
