/**
 * This file is part of ankus.
 *
 * ankus is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * ankus is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with ankus.  If not, see <http://www.gnu.org/licenses/>.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.30 at 02:11:34 오후 KST 
//


package com.ankus.model.workflow;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ankus.model.workflow package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Start_QNAME = new QName("http://www.openankus.org/schema/workflow", "start");
    private final static QName _End_QNAME = new QName("http://www.openankus.org/schema/workflow", "end");
    private final static QName _Action_QNAME = new QName("http://www.openankus.org/schema/workflow", "action");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ankus.model.workflow
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SubWorkflow }
     * 
     */
    public SubWorkflow createSubWorkflow() {
        return new SubWorkflow();
    }

    /**
     * Create an instance of {@link Ftp }
     * 
     */
    public Ftp createFtp() {
        return new Ftp();
    }

    /**
     * Create an instance of {@link Mkdir }
     * 
     */
    public Mkdir createMkdir() {
        return new Mkdir();
    }

    /**
     * Create an instance of {@link ClusterName }
     * 
     */
    public ClusterName createClusterName() {
        return new ClusterName();
    }

    /**
     * Create an instance of {@link Pig }
     * 
     */
    public Pig createPig() {
        return new Pig();
    }

    /**
     * Create an instance of {@link InputPaths }
     * 
     */
    public InputPaths createInputPaths() {
        return new InputPaths();
    }

    /**
     * Create an instance of {@link InputPath }
     * 
     */
    public InputPath createInputPath() {
        return new InputPath();
    }

    /**
     * Create an instance of {@link ClassName }
     * 
     */
    public ClassName createClassName() {
        return new ClassName();
    }

    /**
     * Create an instance of {@link Prepare }
     * 
     */
    public Prepare createPrepare() {
        return new Prepare();
    }

    /**
     * Create an instance of {@link GlobalVariable }
     * 
     */
    public GlobalVariable createGlobalVariable() {
        return new GlobalVariable();
    }

    /**
     * Create an instance of {@link Classpath }
     * 
     */
    public Classpath createClasspath() {
        return new Classpath();
    }

    /**
     * Create an instance of {@link Copy }
     * 
     */
    public Copy createCopy() {
        return new Copy();
    }

    /**
     * Create an instance of {@link Mapreduce }
     * 
     */
    public Mapreduce createMapreduce() {
        return new Mapreduce();
    }

    /**
     * Create an instance of {@link Cluster }
     * 
     */
    public Cluster createCluster() {
        return new Cluster();
    }

    /**
     * Create an instance of {@link Move }
     * 
     */
    public Move createMove() {
        return new Move();
    }

    /**
     * Create an instance of {@link Command }
     * 
     */
    public Command createCommand() {
        return new Command();
    }

    /**
     * Create an instance of {@link Jar }
     * 
     */
    public Jar createJar() {
        return new Jar();
    }

    /**
     * Create an instance of {@link Output }
     * 
     */
    public Output createOutput() {
        return new Output();
    }

    /**
     * Create an instance of {@link Description }
     * 
     */
    public Description createDescription() {
        return new Description();
    }

    /**
     * Create an instance of {@link Compression }
     * 
     */
    public Compression createCompression() {
        return new Compression();
    }

    /**
     * Create an instance of {@link Clusters }
     * 
     */
    public Clusters createClusters() {
        return new Clusters();
    }

    /**
     * Create an instance of {@link Envs }
     * 
     */
    public Envs createEnvs() {
        return new Envs();
    }

    /**
     * Create an instance of {@link Variables }
     * 
     */
    public Variables createVariables() {
        return new Variables();
    }

    /**
     * Create an instance of {@link Shell }
     * 
     */
    public Shell createShell() {
        return new Shell();
    }

    /**
     * Create an instance of {@link Java }
     * 
     */
    public Java createJava() {
        return new Java();
    }

    /**
     * Create an instance of {@link Variable }
     * 
     */
    public Variable createVariable() {
        return new Variable();
    }

    /**
     * Create an instance of {@link NodeType }
     * 
     */
    public NodeType createNodeType() {
        return new NodeType();
    }

    /**
     * Create an instance of {@link Args }
     * 
     */
    public Args createArgs() {
        return new Args();
    }

    /**
     * Create an instance of {@link BaseType }
     * 
     */
    public BaseType createBaseType() {
        return new BaseType();
    }

    /**
     * Create an instance of {@link Delete }
     * 
     */
    public Delete createDelete() {
        return new Delete();
    }

    /**
     * Create an instance of {@link Properties }
     * 
     */
    public Properties createProperties() {
        return new Properties();
    }

    /**
     * Create an instance of {@link OutputPath }
     * 
     */
    public OutputPath createOutputPath() {
        return new OutputPath();
    }

    /**
     * Create an instance of {@link Configuration }
     * 
     */
    public Configuration createConfiguration() {
        return new Configuration();
    }

    /**
     * Create an instance of {@link Hive }
     * 
     */
    public Hive createHive() {
        return new Hive();
    }

    /**
     * Create an instance of {@link Hdfs }
     * 
     */
    public Hdfs createHdfs() {
        return new Hdfs();
    }

    /**
     * Create an instance of {@link GlobalVariables }
     * 
     */
    public GlobalVariables createGlobalVariables() {
        return new GlobalVariables();
    }

    /**
     * Create an instance of {@link Workflow }
     * 
     */
    public Workflow createWorkflow() {
        return new Workflow();
    }

    /**
     * Create an instance of {@link Classpaths }
     * 
     */
    public Classpaths createClasspaths() {
        return new Classpaths();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link ActionType }
     * 
     */
    public ActionType createActionType() {
        return new ActionType();
    }

    /**
     * Create an instance of {@link SubWorkflows }
     * 
     */
    public SubWorkflows createSubWorkflows() {
        return new SubWorkflows();
    }

    /**
     * Create an instance of {@link Input }
     * 
     */
    public Input createInput() {
        return new Input();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NodeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openankus.org/schema/workflow", name = "start")
    public JAXBElement<NodeType> createStart(NodeType value) {
        return new JAXBElement<NodeType>(_Start_QNAME, NodeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BaseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openankus.org/schema/workflow", name = "end")
    public JAXBElement<BaseType> createEnd(BaseType value) {
        return new JAXBElement<BaseType>(_End_QNAME, BaseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openankus.org/schema/workflow", name = "action")
    public JAXBElement<ActionType> createAction(ActionType value) {
        return new JAXBElement<ActionType>(_Action_QNAME, ActionType.class, null, value);
    }

}
